import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createModel } from '../src/prototype/model.mjs';
import { buildDevelopmentPaths, planProgress, activityContext, baselineActivityDraft } from '../src/prototype/development.mjs';
import { restorePlan } from '../src/prototype/workshop-ui.mjs';
import { restoreProgress, saveProgress, STORAGE_KEY } from '../src/prototype/local-progress.mjs';
import { createWorkflows, validatePlanAnswer, validateHrAnswer } from '../scripts/ai/workflows.mjs';
import { createStructuredProvider, readConfig } from '../scripts/ai/provider.mjs';
import { createRecommender } from '../scripts/ai/recommender.mjs';
import { createAppServer, configReader } from '../scripts/serve.mjs';
import { cases } from './fixtures/recommendation-cases.mjs';

const data = JSON.parse(readFileSync(new URL('../src/prototype/data.json', import.meta.url)));
const fixture = structuredClone(cases.find(c => c.id === 'missing-prerequisite').data);
const person = fixture.employees[0];
const planAnswer = path => ({ path_id: path.path_id, title: 'TEST: not generated by AI', summary: 'Explicit transport fixture.',
  steps: path.steps.map(step => ({ event_id: step.event_id, reason: 'TEST: prerequisite checked by code.' })) });
const responseFor = answer => new Response(JSON.stringify({ status: 'completed', output: [{ type: 'message', content: [{ type: 'output_text', text: JSON.stringify(answer) }] }] }));

test('adding just a key enables defaults and hot reload; disabled setting still wins', t => {
  const directory = mkdtempSync(join(tmpdir(), 'career-config-'));
  t.after(() => rmSync(directory, { recursive: true, force: true }));
  const file = join(directory, '.env.local'), config = configReader(file, {});
  const provider = createStructuredProvider({ config });
  assert.equal(provider.status().ready, false);
  writeFileSync(file, 'OPENAI_API_KEY=test-only-not-real');
  assert.equal(provider.status().ready, true);
  assert.equal(config().model, 'gpt-4.1-mini');
  assert.equal(config().baseUrl, 'https://api.openai.com/v1');
  assert.ok(!JSON.stringify(provider.status()).includes('test-only'));
  writeFileSync(file, 'OPENAI_API_KEY=test-only-not-real\nAI_ENABLED=false');
  assert.equal(provider.status().ready, false);
});

test('quest unlocks prerequisite chain, enforces caps, and never mutates source', () => {
  const before = JSON.stringify(fixture), model = createModel(fixture), state = model.snapshot(person);
  const paths = buildDevelopmentPaths(fixture, state, { weeklyHours: 4, maxSteps: 4 });
  const plan = paths[0];
  assert.deepEqual(plan.steps.map(s => s.event_id), ['FOUNDATION', 'ADVANCED']);
  assert.equal(plan.steps[1].prerequisites[0].level, 3);
  assert.equal(planProgress(plan, state).done, 0);
  assert.equal(model.complete(person.employee_id, 'ADVANCED'), false);
  assert.equal(model.complete(person.employee_id, 'FOUNDATION'), true);
  assert.equal(planProgress(plan, model.snapshot(person)).done, 1);
  assert.equal(model.complete(person.employee_id, 'ADVANCED'), true);
  assert.equal(planProgress(plan, model.snapshot(person)).done, 2);
  assert.equal(model.snapshot(person).coverage, plan.coverageAfter);
  model.setGoal(person.employee_id, 'Data Analyst', 'Middle');
  assert.equal(planProgress(plan, model.snapshot(person)).valid, false);
  assert.equal(JSON.stringify(fixture), before);
  assert.ok(plan.statChanges.every(s => s.after <= 5));
});

test('scheduled steps cannot start before previous step ends; weekly load changes estimates', () => {
  const sample = structuredClone(fixture);
  sample.events[0].format = 'online'; sample.events[0].upcoming_sessions = ['2026-10-02'];
  let paths = buildDevelopmentPaths(sample, createModel(sample).snapshot(sample.employees[0]));
  assert.deepEqual(paths[0].steps.map(s => s.event_id), ['FOUNDATION']);
  sample.events[0].upcoming_sessions.push('2026-10-10');
  paths = buildDevelopmentPaths(sample, createModel(sample).snapshot(sample.employees[0]));
  assert.deepEqual(paths[0].steps.map(s => s.event_id), ['FOUNDATION', 'ADVANCED']);
  assert.ok(paths[0].steps[1].start >= paths[0].steps[0].end);
  const slow = buildDevelopmentPaths(fixture, createModel(fixture).snapshot(person), { weeklyHours: 1 })[0];
  assert.ok(slow.end > paths[0].end);
});

test('focus skill changes first step; missing courses and invalid settings are explicit', () => {
  const sample = cases[0].data, state = createModel(sample).snapshot(sample.employees[0]);
  const plan = buildDevelopmentPaths(sample, state, { focusSkill: 'SPEAK', maxSteps: 1 })[0];
  assert.equal(plan.steps[0].event_id, 'SPEAK_STEP');
  assert.throws(() => buildDevelopmentPaths(sample, state, { focusSkill: 'unknown' }));
  assert.throws(() => buildDevelopmentPaths(sample, state, { weeklyHours: 0 }));
  const empty = cases.at(-1).data;
  assert.deepEqual(buildDevelopmentPaths(empty, createModel(empty).snapshot(empty.employees[0])), []);
});

test('every dataset path is playable in order with monotonic coverage and honest progress', () => {
  const source = JSON.stringify(data), model = createModel(data);
  let plans = 0;
  for (const employee of data.employees) {
    const plan = buildDevelopmentPaths(data, model.snapshot(employee))[0];
    if (!plan) continue;
    plans++;
    const simulation = createModel(data);
    for (const [i, step] of plan.steps.entries()) {
      assert.equal(planProgress(plan, simulation.snapshot(employee)).done, i);
      assert.equal(simulation.complete(employee.employee_id, step.event_id), true);
      assert.equal(step.coverageAfter, simulation.snapshot(employee).coverage);
      assert.ok(step.coverageAfter >= step.coverageBefore);
      if (i) assert.ok(step.start >= plan.steps[i - 1].end);
    }
  }
  assert.ok(plans > 0); assert.equal(JSON.stringify(data), source);
});

test('AI cannot invent plan steps, reorder prerequisites or replace numerical gains', () => {
  const paths = buildDevelopmentPaths(fixture, createModel(fixture).snapshot(person));
  const answer = planAnswer(paths[0]);
  answer.coverageAfter = 100; answer.steps[0].impact = [{ after: 999 }];
  const result = validatePlanAnswer(answer, paths);
  assert.equal(result.coverageAfter, paths[0].coverageAfter);
  assert.deepEqual(result.steps[0].impact, paths[0].steps[0].impact);
  answer.steps.reverse(); assert.throws(() => validatePlanAnswer(answer, paths));
});

test('HR drafts cite available aggregate evidence, respect time budget, and cannot change gains', () => {
  const before = JSON.stringify(data);
  for (const event of data.events.filter(e => !e.mandatory)) {
    const ctx = activityContext(data, event.event_id), draft = baselineActivityDraft(ctx);
    assert.deepEqual(validateHrAnswer(draft, ctx), draft);
    for (const person of data.employees) assert.ok(!JSON.stringify(ctx).includes(person.full_name));
    const invented = structuredClone(draft); invented.improvements[0].evidence_ids = ['fake'];
    assert.throws(() => validateHrAnswer(invented, ctx));
    const overtime = structuredClone(draft); overtime.agenda[0].minutes += 5000;
    assert.throws(() => validateHrAnswer(overtime, ctx));
    const foreignSkill = structuredClone(draft); foreignSkill.agenda[0].skill_ids = ['FAKE'];
    assert.throws(() => validateHrAnswer(foreignSkill, ctx));
    draft.develops_skills = [{ gain: 999 }];
    assert.equal(validateHrAnswer(draft, ctx).develops_skills, undefined);
  }
  assert.throws(() => activityContext(data, 'EV_001'));
  assert.equal(JSON.stringify(data), before);
});

test('both workflows use shared strict transport and honest fallback without a key', async () => {
  let calls = 0;
  const provider = createStructuredProvider({ config: readConfig({ OPENAI_API_KEY: 'test-only' }), fetchImpl: async (_url, options) => {
    calls++;
    const body = JSON.parse(options.body), input = JSON.parse(body.input);
    assert.equal(body.store, false); assert.equal(body.text.format.strict, true);
    assert.ok(!JSON.stringify(input).includes(person.full_name));
    return responseFor(body.text.format.name === 'development_plan' ? planAnswer(input.paths[0]) : baselineActivityDraft(activityContext(fixture, 'FOUNDATION')));
  } });
  const workflows = createWorkflows({ data: fixture, provider });
  assert.equal((await workflows.developmentPlan({ employeeId: person.employee_id })).source, 'ai');
  assert.equal((await workflows.improveActivity({ eventId: 'FOUNDATION', brief: 'Add practice' })).source, 'ai');
  assert.equal(calls, 2);
  const offline = createWorkflows({ data: fixture, provider: createStructuredProvider({ config: readConfig({}), fetchImpl: () => assert.fail('must not call externally') }) });
  assert.equal((await offline.developmentPlan({ employeeId: person.employee_id })).source, 'rules');
  assert.equal((await offline.improveActivity({ eventId: 'FOUNDATION', brief: '' })).source, 'rules');
});

test('local progress survives reload and ignores corrupt or different dataset data', () => {
  let value; const storage = { getItem: () => value, setItem: (key, data) => { assert.equal(key, STORAGE_KEY); value = data; } };
  const restored = restoreProgress(fixture, storage), model = restored.model;
  const plan = buildDevelopmentPaths(fixture, model.snapshot(person))[0];
  model.complete(person.employee_id, 'FOUNDATION');
  assert.equal(saveProgress(fixture, model, { ...restored, plans: { SYNTHETIC: { source: 'rules', plan } } }, storage), true);
  const next = restoreProgress(fixture, storage);
  assert.deepEqual(next.model.snapshot(person).simulated, ['FOUNDATION']);
  const record = restorePlan(fixture, next.plans.SYNTHETIC, person);
  assert.equal(planProgress(record.plan, next.model.snapshot(person)).done, 1);
  next.plans.SYNTHETIC.plan.coverageAfter = 999;
  assert.equal(restorePlan(fixture, next.plans.SYNTHETIC, person).plan.coverageAfter, plan.coverageAfter);
  assert.equal(restoreProgress({ ...fixture, asOf: '2027-01-01' }, storage).model.snapshot(person).simulated.length, 0);
  value = '{broken'; assert.equal(restoreProgress(fixture, storage).model.snapshot(person).simulated.length, 0);
  assert.equal(restorePlan(fixture, { plan: { steps: 5 } }, person), null);
  assert.equal(saveProgress(fixture, model, restored, { setItem: () => { throw new Error('quota'); } }), false);
});

test('HTTP exposes both workflows and validates inputs without exposing credentials', async t => {
  const provider = createStructuredProvider({ config: readConfig({}) });
  const server = createAppServer({ data, recommender: createRecommender({ provider }), workflows: createWorkflows({ data, provider }) });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  t.after(() => new Promise(resolve => { server.closeAllConnections(); server.close(resolve); }));
  const url = `http://127.0.0.1:${server.address().port}`;
  const post = (path, body) => fetch(url + path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  assert.ok((await (await post('/api/development-plan', { employeeId: 'E0005' })).json()).plan.steps.length);
  assert.ok((await (await post('/api/hr/improve-activity', { eventId: 'EV_005', brief: '' })).json()).draft.agenda.length);
  assert.equal((await post('/api/development-plan', { employeeId: 'E0005', options: { maxSteps: 99 } })).status, 400);
  assert.equal((await post('/api/hr/improve-activity', { eventId: 'EV_001', brief: '' })).status, 400);
  for (const path of ['/workshop-ui.mjs', '/local-progress.mjs', '/development.mjs']) assert.equal((await fetch(url + path)).status, 200);
  assert.equal((await fetch(url + '/.env.local')).status, 404);
});
